ARG DEBIAN_VERSION=bookworm-slim
FROM debian:${DEBIAN_VERSION}

LABEL org.opencontainers.image.title="dev-proxy"
LABEL org.opencontainers.image.description="Contains Microsoft Dev Proxy with pre-loaded and updated Microsoft Graph API metadata."
LABEL org.opencontainers.image.version="0.21.0"
LABEL org.opencontainers.image.url="https://hub.docker.com/repository/docker/cfelipe/dev-proxy"
LABEL org.opencontainers.image.source="https://github.com/CarlosDomingues/dev-proxy-images"
LABEL org.opencontainers.image.created="2024-10-19T00:00:00Z"
LABEL org.opencontainers.image.authors="Carlos Domingues <11181378+CarlosDomingues@users.noreply.github.com>"
LABEL org.opencontainers.image.documentation="https://github.com/CarlosDomingues/dev-proxy-images?tab=readme-ov-file#usage"
LABEL org.opencontainers.image.licenses="MIT"

ENV DEBIAN_FRONTEND=noninteractive

ARG DEVPROXY_VERSION=v0.21.0

RUN apt-get update \
    && apt-get install --yes curl unzip libicu-dev \
    && curl -sL https://raw.githubusercontent.com/microsoft/dev-proxy/${DEVPROXY_VERSION}/scripts/setup.sh | bash \
    && apt-get remove --purge --yes curl unzip \
    && apt-get autoremove --yes \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN groupadd --gid 1001 devproxygroup \
    && useradd --uid 1001 --gid devproxygroup --shell /bin/bash --create-home devproxyuser \
    && chown -R devproxyuser:devproxygroup /devproxy /home/devproxyuser

USER devproxyuser
RUN /devproxy/devproxy msgraphdb

ENV DEVPROXY_PORT=8000
ENV DEVPROXY_PRESET=/devproxy/presets/m365.json
ENV DEV_PROXY_LOG_LEVEL=Information

EXPOSE ${DEVPROXY_PORT}
EXPOSE 8897

CMD ["bash", "-c", "/devproxy/devproxy --config-file ${DEVPROXY_PRESET} --ip-address 0.0.0.0 --port ${DEVPROXY_PORT} --log-level ${DEV_PROXY_LOG_LEVEL}"]
